config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :items  do# 8條路徑
    member do
      post :add_to_cart
    end
    resources :comments, only: [:create]
  end
  # resources :comments
  # # /comments 看到所有留言
  # # /comments/:id 
  # # /comments/new
  # # /comments/create
  # # .comments/edit

  #cart
  # post "/abc/id", to "cart#add", as: :cc # 請你幫我做一個path 出來/
  resource :cart, only: [:show, :destroy]  do# 做出單數的東西/ rescource 沒加s
    collection do  # 新增購物車的結帳頁面
      get :checkout
    end
  end

# 
  resource :orders, only: [:index, :show, :create] do
    member do
      delete :cancel
    end
  end


  #/users/edit
  #/usrs/3/edit
  # user
  # get "/", to: "welcome#index"
  # 泛用型的寫法
  get '/login', to: "users#login"
  post '/login', to: 'users#sign_in'
  delete "/logout", to: "users#logout"
  get '/sign_up', to: "users#sign_up"
  post '/sign_up', to: "users#registration"
  # get post put patch delete (現在瀏覽器只有get/post 這兩個動作)
  # 方法   controller 見一個檔案
  
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do 
          post :favorite
        end
        # collection do 
        #   get :all
        # end
      end
    end
  end
end

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert" data-controller="flash" data-target="flash.message">
    <%= notice %>
    <button type="button" class="close" data-action="flash#close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-success" role="alert" data-controller="flash" data-target="flash.message">
    <%= alert %>
    <button type="button" class="close" data-action="flash#close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer font-small bg-light mt-2">
  <div class="footer-copyright text-center py-2">2020 &copy;
    <%= link_to "吃飯", root_path %>
  </div>
</footer> 

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">訂便當</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "餐點列表", items_path, class: 'nav-link' %>
      </li>

      <% if current_user %>
        <li class="nav-item">
          <%= link_to "我要開團", "#", class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <a href="/sign_up" class="nav-link">註冊</a>
        </li>
        <li class="nav-item">
          <a href="/login" class="nav-link">登入</a>
        </li>
      <% end %>
    </ul>

    <% if current_user %>
    <ul class="navbar-nav">
      <li>
        <%= link_to cart_path, class: 'nav-link' do %>
          購物車 <i class="fas fa-shopping-cart"></i> 
        <%= current_cart.items.count %>
        <% end %>
      </li>
      <li>
        <a href="#" class="nav-link">你好，<%= current_user.email %></a>
      </li>
      <li class="nav-item">
        <%= link_to "登出", logout_path, method: 'delete', class: 'nav-link' %>
      </li>
    </ul>
    <% end %>
  </div>
</nav>