config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :items  do# 8條路徑
    member do
      post :add_to_cart
    end
    resources :comments, only: [:create]
  end
  # resources :comments
  # # /comments 看到所有留言
  # # /comments/:id 
  # # /comments/new
  # # /comments/create
  # # .comments/edit

  #cart
  # post "/abc/id", to "cart#add", as: :cc # 請你幫我做一個path 出來/
  resource :cart, only: [:show, :destroy]  do# 做出單數的東西/ rescource 沒加s
    collection do  # 新增購物車的結帳頁面
      get :checkout
    end
  end

# 
  resource :orders, only: [:index, :show, :create] do
    member do
      delete :cancel
    end
  end


  #/users/edit
  #/usrs/3/edit
  # user
  # get "/", to: "welcome#index"
  # 泛用型的寫法
  get '/login', to: "users#login"
  post '/login', to: 'users#sign_in'
  delete "/logout", to: "users#logout"
  get '/sign_up', to: "users#sign_up"
  post '/sign_up', to: "users#registration"
  # get post put patch delete (現在瀏覽器只有get/post 這兩個動作)
  # 方法   controller 見一個檔案
  
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do 
          post :favorite
        end
        # collection do 
        #   get :all
        # end
      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true,
                    numericality: { greater_than: 0 }

  has_many :comments                    
  belongs_to :category
  has_many :favorite_items
  has_many :users, through: :favorite_items

  has_one_attached :cover
  
  # scope :available,  -> { where(deleted_at: nil) }
  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.now)
  end

  def favorited_by(u)
    u.items.include?(self)
  end

end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < ApplicationController
  # skip_before_action :verify_authenticity_token
  # skip_before_action :check_login
  # 忽略不是一個好的做法
  def favorite
    item = Item.find(params[:id])
    
    if item.favorited_by(current_user)
      #移除最愛
      # FavoriteItem.find_by(item: item, user: current_user).destroy
      current_user.items.delete(item)
      render json: {status: 'removed'}
    else
      current_user.items << item
      render json: {status: 'favorited'}
    end
    # item = Item.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy, :add_to_cart]

  def index
    @items = Item.all
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user) #eager loading
  end

  def new
    @item = Item.new  
  end

  def create
    @item = Item.new(item_params)
    
    if  @item.save
      # flash[:notice] = "成功新增餐點"
      # redirect_to items_path
      redirect_to items_path , notice: '成功新增餐點'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to items_path, notice: "成功更新餐點"
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    # @item.update(deleted_at: Time.now)
    redirect_to items_path, notice: '成功刪除餐點'
  end

  def add_to_cart
    current_cart.add_item(@item.id)
    session[:carty] = current_cart.to_hash
    redirect_to root_path , notice: "已加到購物車"
  end

  private
  def find_item
    @item = Item.find(params[:id])
    # @item = Item.find_by!(id: params[:id], deleted_at: nil )
  end
  def item_params
    params.require(:item).permit( :name,
                                  :description,
                                  :price,
                                  :cover,
                                  :category_id, #放行進來
                                  :spec )
  end
end

app/helpers/api/vi/items_helper.rb
module Api::Vi::ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
      </ul>
  <% end%>

  <div>
    <%= f.label :cover %>
    <%= f.file_field :cover %>
  </div>

  <div>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name   %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.label :spec %>
    <%= f.text_field :spec %>
  </div>

  <%= f.submit %>
  

  
<% end %>

app/views/items/edit.html.erb
<h1>修改餐點</h1>

<%= render 'form', item: @item %>

app/views/items/index.html.erb
<h1 class="text-center my-3">餐點列表</h1>

<%= link_to "新增",  new_item_path %> 

<%= t('a.b.c')%>

<div class="row my-3">
    <% @items.each do |item| %>
      <div class="col-12 col-md-4 item">
        <div class="card my-3">
          <div class="cover-img overflow-hidden">
            <%= image_tag item.cover.variant(resize_to_limit: [500, 500])  if item.cover.attached? %>
            <%# <img src="https://picsum.photos/1000/600?random=2" class> %>
          </div>
          
          <div class="card-body">
            <h5 class="card-title text-center">
              <%= item.category.name %>
            </h5>
            <p>
              <%= link_to item.name, item_path(item.id)%>
            </p>
            <p>
              <%= link_to "修改", edit_item_path(item.id), class: "btn btn-primary" %>
              <%= link_to "刪除", item_path(item.id), 
                  method: 'delete',class: "btn btn-danger" , data: { 
                  confirm: 'Are you Sure?'
                  } %>
              <%= link_to "加到購物車", add_to_cart_item_path(item), method: 'post', class: "btn btn-success" %>
            </p>
            </div>
          </div>
      </div>
    <% end %>
</div>

app/views/items/new.html.erb
<h1>新增餐點</h1>

<%= render 'form', item: @item %>

<%# render partial: 'form', locals: { item: @item } %>





<%#   t.string :name
      t.text :description
      t.integer :price
      t.string :spec %>

app/views/items/show.html.erb
<h1 data-controller="item" ><%= @item.name %>(<%= @item.price %>元)
  <a href='#' class="btn btn-dark" data-action="item#heart" >
    <% if @item.favorited_by(current_user) %>
      <i class="fas fa-heart" data-target="item.icon"></i>
    <% else %>
      <i class="far fa-heart" data-target="item.icon"></i>
    <% end %>
  </a>
</h1>

<%= image_tag @item.cover.variant(resize_to_limit: [800, 500]), class: 'cover-image' if @item.cover.attached? %>

<div data-controller="comment">
  <h3>留言</h3>
<%= form_for(@comment, url: item_comments_path(@item), remote: true ) do |form| %>
  <input type="hidden" id="item_id" value="<%= @item.id %>">
  <div class="form-group">
    <%= form.text_area :content,
                        class: 'form-control',
                        data: {target: 'comment.content', 
                              action: 'keyup->comment#check'} %>
  </div>

  <%= form.submit class: 'btn btn-info',disabled: true, data: {target: 'comment.submit'} %>
<% end %>

<hr>
<div id="comments"></div>

<% @comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>
</div>